paths:
  uploads: static/uploads
  static: static
  collections: content
  data: data
  layouts:
collections_config: {}
_enabled_editors:
  - content
  - data
  - visual
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
